version: '3.4'

services:
  trendyol-study-case:
    image: trendyol-study-case
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysql-db:3306/trendyol_study_case?allowPublicKeyRetrieval=true&useSSL=false",
              "spring.datasource.username" : "user",
              "spring.datasource.password" : "admin",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'

  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=trendyol_study_case
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin