version: '2.1'

services:
  trendyol-study-case:
    image: trendyol-study-case
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_NAME=trendyol_study_case
      - DB_USER=user
      - DB_PASSWORD=admin

  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=trendyol_study_case
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD